/* ============================================================
   TravelNest – Shared destination data
   ============================================================ */
'use strict';

const DESTINATIONS = [
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    travelTypes: ['beach', 'cultural', 'romantic'],
    budgetTier: 'moderate',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    description: 'Perched on volcanic cliffs above the Aegean Sea, Santorini is one of the most romanticised destinations in the world. Its iconic blue-domed churches, whitewashed villages, and breathtaking caldera views make it a bucket-list destination for couples and solo travellers alike. The island was shaped by a massive volcanic eruption around 1600 BC, giving it its distinctive crescent shape and dramatic cliffs.',
    attractions: [
      'Oia Sunset — the most photographed sunset in the world',
      'Fira Caldera Walk — a dramatic cliff-top promenade with panoramic views',
      'Red Beach — striking volcanic red cliffs meeting turquoise water',
      'Akrotiri Archaeological Site — a preserved Bronze Age Minoan city',
      'Santo Wines — wine tasting overlooking the caldera',
      'Volcano boat tour — hike the active Nea Kameni crater',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [50,  25, 15, 10],
      moderate: [150, 60, 35, 40],
      luxury:   [400, 150, 80, 120],
    },
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    travelTypes: ['cultural', 'nature', 'adventure'],
    budgetTier: 'budget',
    image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
    description: 'Once the imperial capital of Japan, Kyoto is a city where ancient tradition and modern life coexist in perfect harmony. Home to over 1,600 Buddhist temples, 400 Shinto shrines, and 17 UNESCO World Heritage Sites, the city bursts with cultural treasures. Spring brings the magical cherry blossom season, while autumn transforms the forested hillsides into a vivid tapestry of red, orange, and gold.',
    attractions: [
      'Fushimi Inari Shrine — thousands of vermillion torii gates climbing Mount Inari',
      'Arashiyama Bamboo Grove — a serene walk through towering bamboo',
      'Kinkaku-ji (Golden Pavilion) — a Zen temple covered in gold leaf',
      'Gion District — historic geisha quarter with traditional machiya townhouses',
      'Nishiki Market — Kyoto\'s vibrant "Kitchen" street market',
      'Philosopher\'s Path — a scenic canal walk lined with cherry trees',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [40,  20, 10, 15],
      moderate: [120, 50, 25, 35],
      luxury:   [350, 120, 60, 100],
    },
  },
  {
    id: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    continent: 'South America',
    travelTypes: ['adventure', 'cultural', 'nature'],
    budgetTier: 'moderate',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'Rising 2,430 metres above sea level in the Peruvian Andes, Machu Picchu is one of humanity\'s most awe-inspiring achievements. Built by the Inca Empire in the 15th century and later abandoned, this "Lost City" was only reintroduced to the world in 1911. Surrounded by cloud forest and dramatic mountain peaks, its stone terraces and temples feel like a portal to another world.',
    attractions: [
      'Sun Gate (Inti Punku) — the original Inca trail entrance with panoramic views',
      'Temple of the Sun — the most sacred Inca astronomical observatory',
      'Huayna Picchu hike — steep trail rewarded with breathtaking aerial views',
      'Inca Bridge — a dizzying narrow path carved into a cliff face',
      'Sacred Valley — markets and Inca ruins stretching towards Cusco',
      'Rainbow Mountain (Vinicunca) — a vivid striped peak at 5,200m',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [30, 15, 20, 25],
      moderate: [90, 40, 45, 60],
      luxury:   [250, 100, 80, 150],
    },
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'USA',
    continent: 'North America',
    travelTypes: ['city', 'cultural', 'adventure'],
    budgetTier: 'luxury',
    image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805ef8?w=800&q=80',
    description: 'New York City is the city that never sleeps — a relentless engine of culture, commerce, and creativity. Spread across five boroughs and 302 square miles, it is home to 8.3 million people from every corner of the globe. From the neon spectacle of Times Square to the peaceful greenery of Central Park, from world-class museums to the hottest restaurants on the planet, NYC offers something for every type of traveller.',
    attractions: [
      'Central Park — 843 acres of greenery in the heart of Manhattan',
      'The Metropolitan Museum of Art — one of the world\'s largest art museums',
      'High Line — an elevated park built on a historic freight rail line',
      'Brooklyn Bridge — iconic suspension bridge with sweeping skyline views',
      'One World Observatory — the tallest building in the Western Hemisphere',
      'Statue of Liberty & Ellis Island — symbols of American freedom and immigration',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [80,  30, 20, 15],
      moderate: [200, 80, 40, 50],
      luxury:   [600, 200, 100, 150],
    },
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    continent: 'Africa',
    travelTypes: ['cultural', 'adventure'],
    budgetTier: 'budget',
    image: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800&q=80',
    description: 'Marrakech is a city that assaults the senses in the most wonderful way. Step through the ancient walls of the Medina and you are transported into a labyrinth of souks, street food stalls, and riads — traditional homes with lush internal courtyards. The beating heart of the city is Djemaa el-Fna, a vast square that transforms from a morning market into a dazzling carnival of storytellers, snake charmers, and food vendors each evening.',
    attractions: [
      'Djemaa el-Fna — the world\'s greatest open-air theatre and market square',
      'Majorelle Garden — an electric-blue garden oasis once owned by Yves Saint Laurent',
      'Bahia Palace — a stunning 19th-century palace with intricate tilework',
      'Medina Souks — a maze of craft markets selling spices, leather, and textiles',
      'Koutoubia Mosque — the largest mosque in Marrakech with a towering minaret',
      'Atlas Mountains day trip — snow-capped peaks just an hour from the city',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [20, 10, 5,  15],
      moderate: [70, 30, 15, 30],
      luxury:   [200, 80, 40, 80],
    },
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    travelTypes: ['beach', 'cultural', 'nature'],
    budgetTier: 'budget',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    description: 'Bali is the Island of the Gods, a place of extraordinary beauty where rice paddies cascade down volcanic hillsides, ancient temples cling to clifftops, and the sea glitters in a hundred shades of blue. It is also a place of deep spiritual life — the Balinese Hindu tradition permeates every aspect of daily life, from the tiny flower offerings placed on doorsteps each morning to the grand festivals that fill the island\'s calendar.',
    attractions: [
      'Tanah Lot Temple — a sea temple perched on a rock surrounded by ocean',
      'Tegallalang Rice Terraces — UNESCO-listed emerald terraces near Ubud',
      'Sacred Monkey Forest Sanctuary — ancient temple complex inhabited by macaques',
      'Seminyak Beach — sunset drinks and world-class surf breaks',
      'Mount Batur sunrise trek — a 3am hike to watch the sunrise from a volcanic crater',
      'Tirta Empul — a sacred Hindu water temple used for ritual purification',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [25, 15, 10, 10],
      moderate: [80, 35, 20, 30],
      luxury:   [300, 100, 50, 80],
    },
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    continent: 'Oceania',
    travelTypes: ['adventure', 'nature'],
    budgetTier: 'moderate',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80',
    description: 'Queenstown is the adventure capital of the world — a vibrant resort town nestled on the shores of Lake Wakatipu, encircled by the jagged peaks of the Remarkables mountain range. Whether you\'re bungee jumping from the Kawarau Bridge where the sport was invented, skiing world-class slopes, or simply hiking through some of the planet\'s most dramatic scenery, Queenstown sets the pulse racing.',
    attractions: [
      'Bungee jumping at Kawarau Bridge — the world\'s first commercial bungee site',
      'Milford Sound cruise — a fiord sculpted by glaciers of extraordinary beauty',
      'The Remarkables ski fields — world-class skiing right above the town',
      'Shotover Jet — white-knuckle jet-boat rides through narrow canyon gorges',
      'Ben Lomond hike — a 3-hour trail with sweeping views over Lake Wakatipu',
      'Arrowtown — a charming gold-rush-era town just 20 minutes away',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [60,  30, 15, 40],
      moderate: [150, 70, 30, 80],
      luxury:   [400, 150, 60, 200],
    },
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    travelTypes: ['nature', 'cultural', 'adventure', 'beach'],
    budgetTier: 'budget',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
    description: 'Cape Town is arguably Africa\'s most beautiful city — a place where dramatic Table Mountain rises above a glittering bay, pristine beaches stretch for miles, and a rich, complex history has forged one of the most diverse cultures on the continent. World-class wine country lies just 45 minutes from the city, while whale watching, shark cage diving, and penguin colonies are all within easy reach.',
    attractions: [
      'Table Mountain — take the aerial cableway for extraordinary 360° views',
      'Boulders Beach Penguin Colony — a colony of 3,000 African penguins',
      'Cape Point — the dramatic meeting point of the Atlantic and Indian oceans',
      'Robben Island — the prison where Nelson Mandela was held for 18 years',
      'Stellenbosch Wine Route — rolling vineyards producing world-class wines',
      'V&A Waterfront — a vibrant harbour district of restaurants, markets, and culture',
    ],
    costs: {
      categories: ['Accommodation /night', 'Food /day', 'Local transport /day', 'Activities /day'],
      budget:   [35, 20, 15, 20],
      moderate: [100, 50, 30, 50],
      luxury:   [300, 120, 60, 100],
    },
  },
];
